### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bijumon** [javsanpar/storytel-tui#4]
I can login to the app and the website
builds ok but exits after login
no idea if it succeded or failed

rustc 1.54.0
openssl  1.1.1.k-1
mpv 0.33.1-2

```
$ ldd ./target/debug/storytel-tui
	linux-vdso.so.1 (0x00007ffde2664000)
	libmpv.so.1 => /usr/lib/libmpv.so.1 (0x00007fd3aeb51000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007fd3aeac0000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007fd3ae7e2000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fd3ae7c7000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fd3ae7a6000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fd3ae662000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fd3ae659000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fd3ae48d000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fd3af725000)
	liblua5.2.so.5.2 => /usr/lib/liblua5.2.so.5.2 (0x00007fd3ae459000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x00007fd3ae371000)
	libcaca.so.0 => /usr/lib/libcaca.so.0 (0x00007fd3ae2a4000)
	libcdio_paranoia.so.2 => /usr/lib/libcdio_paranoia.so.2 (0x00007fd3ae29a000)
	libcdio_cdda.so.2 => /usr/lib/libcdio_cdda.so.2 (0x00007fd3ae28e000)
	libcdio.so.19 => /usr/lib/libcdio.so.19 (0x00007fd3ae262000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007fd3ae24d000)
	libdvdnav.so.4 => /usr/lib/libdvdnav.so.4 (0x00007fd3ae235000)
	libdvdread.so.8 => /usr/lib/libdvdread.so.8 (0x00007fd3ae212000)
	libEGL.so.1 => /usr/lib/libEGL.so.1 (0x00007fd3ae200000)
	libavutil.so.56 => /usr/lib/libavutil.so.56 (0x00007fd3adf53000)
	libavcodec.so.58 => /usr/lib/libavcodec.so.58 (0x00007fd3acb1a000)
	libavformat.so.58 => /usr/lib/libavformat.so.58 (0x00007fd3ac881000)
	libswscale.so.5 => /usr/lib/libswscale.so.5 (0x00007fd3ac7ef000)
	libavfilter.so.7 => /usr/lib/libavfilter.so.7 (0x00007fd3ac39d000)
	libswresample.so.3 => /usr/lib/libswresample.so.3 (0x00007fd3ac37e000)
	libgbm.so.1 => /usr/lib/libgbm.so.1 (0x00007fd3ac36c000)
	libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007fd3ac367000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007fd3ac355000)
	libjack.so.0 => /usr/lib/libjack.so.0 (0x00007fd3ac303000)
	libmujs.so => /usr/lib/libmujs.so (0x00007fd3ac2b9000)
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007fd3ac22f000)
	liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x00007fd3ac1cb000)
	libarchive.so.13 => /usr/lib/libarchive.so.13 (0x00007fd3ac108000)
	libass.so.9 => /usr/lib/libass.so.9 (0x00007fd3ac0d1000)
	libavdevice.so.58 => /usr/lib/libavdevice.so.58 (0x00007fd3ac0ad000)
	libbluray.so.2 => /usr/lib/libbluray.so.2 (0x00007fd3ac05a000)
	libplacebo.so.120 => /usr/lib/libplacebo.so.120 (0x00007fd3abfce000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fd3abfc1000)
	libpulse.so.0 => /usr/lib/libpulse.so.0 (0x00007fd3abf6c000)
	librubberband.so.2 => /usr/lib/librubberband.so.2 (0x00007fd3abf34000)
	libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x00007fd3abcef000)
	libsamplerate.so.0 => /usr/lib/libsamplerate.so.0 (0x00007fd3abb80000)
	libshaderc_shared.so.1 => /usr/lib/libshaderc_shared.so.1 (0x00007fd3abb65000)
	libuchardet.so.0 => /usr/lib/libuchardet.so.0 (0x00007fd3abb31000)
	libva.so.2 => /usr/lib/libva.so.2 (0x00007fd3abb04000)
	libva-drm.so.2 => /usr/lib/libva-drm.so.2 (0x00007fd3abaff000)
	libva-wayland.so.2 => /usr/lib/libva-wayland.so.2 (0x00007fd3abaf9000)
	libva-x11.so.2 => /usr/lib/libva-x11.so.2 (0x00007fd3abaf1000)
	libvdpau.so.1 => /usr/lib/libvdpau.so.1 (0x00007fd3abaec000)
	libvulkan.so.1 => /usr/lib/libvulkan.so.1 (0x00007fd3aba89000)
	libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007fd3aba80000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007fd3aba38000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fd3ab8f7000)
	libXss.so.1 => /usr/lib/libXss.so.1 (0x00007fd3ab8f2000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fd3ab8dd000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007fd3ab8d6000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007fd3ab8c9000)
	libXv.so.1 => /usr/lib/libXv.so.1 (0x00007fd3ab8c1000)
	libzimg.so.2 => /usr/lib/libzimg.so.2 (0x00007fd3ab7f0000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fd3ab7d6000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fd3ab764000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fd3ab6ac000)
	libmfx.so.1 => /usr/lib/libmfx.so.1 (0x00007fd3ab69e000)
	libvpx.so.6 => /usr/lib/libvpx.so.6 (0x00007fd3ab397000)
	libwebpmux.so.3 => /usr/lib/libwebpmux.so.3 (0x00007fd3ab38b000)
	libwebp.so.7 => /usr/lib/libwebp.so.7 (0x00007fd3ab31a000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fd3ab2f2000)
	libdav1d.so.5 => /usr/lib/libdav1d.so.5 (0x00007fd3ab195000)
	libopencore-amrwb.so.0 => /usr/lib/libopencore-amrwb.so.0 (0x00007fd3ab17f000)
	librsvg-2.so.2 => /usr/lib/librsvg-2.so.2 (0x00007fd3aa8fb000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007fd3aa8a1000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fd3aa76a000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007fd3aa64b000)
	libaom.so.3 => /usr/lib/libaom.so.3 (0x00007fd3a9eeb000)
	libgsm.so.1 => /usr/lib/libgsm.so.1 (0x00007fd3a9edc000)
	libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x00007fd3a9e64000)
	libopencore-amrnb.so.0 => /usr/lib/libopencore-amrnb.so.0 (0x00007fd3a9e38000)
	libopenjp2.so.7 => /usr/lib/libopenjp2.so.7 (0x00007fd3a9dd4000)
	libopus.so.0 => /usr/lib/libopus.so.0 (0x00007fd3a9d76000)
	librav1e.so.0 => /usr/lib/librav1e.so.0 (0x00007fd3a9b24000)
	libspeex.so.1 => /usr/lib/libspeex.so.1 (0x00007fd3a9b09000)
	libSvtAv1Enc.so.0 => /usr/lib/libSvtAv1Enc.so.0 (0x00007fd3a0c7f000)
	libtheoraenc.so.1 => /usr/lib/libtheoraenc.so.1 (0x00007fd3a0c46000)
	libtheoradec.so.1 => /usr/lib/libtheoradec.so.1 (0x00007fd3a0c2b000)
	libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007fd3a0bfd000)
	libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007fd3a0b52000)
	libx264.so.161 => /usr/lib/libx264.so.161 (0x00007fd3a0892000)
	libx265.so.199 => /usr/lib/libx265.so.199 (0x00007fd39f5fc000)
	libxvidcore.so.4 => /usr/lib/libxvidcore.so.4 (0x00007fd39f4ed000)
	libxml2.so.2 => /usr/lib/libxml2.so.2 (0x00007fd39f37d000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fd39f36a000)
	libmodplug.so.1 => /usr/lib/libmodplug.so.1 (0x00007fd39f1da000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007fd39f13a000)
	libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x00007fd39ef39000)
	libsrt.so.1.4 => /usr/lib/libsrt.so.1.4 (0x00007fd39ee66000)
	libssh.so.4 => /usr/lib/libssh.so.4 (0x00007fd39edfa000)
	libpostproc.so.55 => /usr/lib/libpostproc.so.55 (0x00007fd39edd9000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007fd39edba000)
	libvmaf.so.0 => /usr/lib/libvmaf.so.0 (0x00007fd39ec9d000)
	libvidstab.so.1.1 => /usr/lib/libvidstab.so.1.1 (0x00007fd39ec88000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fd39ec37000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fd39eb63000)
	libsoxr.so.0 => /usr/lib/libsoxr.so.0 (0x00007fd39eae1000)
	libwayland-server.so.0 => /usr/lib/libwayland-server.so.0 (0x00007fd39eaca000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fd39ea9a000)
	libffi.so.7 => /usr/lib/libffi.so.7 (0x00007fd39ea8c000)
	libdb-5.3.so => /usr/lib/libdb-5.3.so (0x00007fd39e8cd000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fd39e6b7000)
	libacl.so.1 => /usr/lib/libacl.so.1 (0x00007fd39e6ac000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007fd39e59d000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007fd39e57a000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fd39e4a3000)
	libraw1394.so.11 => /usr/lib/libraw1394.so.11 (0x00007fd39e491000)
	libavc1394.so.0 => /usr/lib/libavc1394.so.0 (0x00007fd39e48a000)
	librom1394.so.0 => /usr/lib/librom1394.so.0 (0x00007fd39e484000)
	libiec61883.so.0 => /usr/lib/libiec61883.so.0 (0x00007fd39e476000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fd39e44c000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007fd39e445000)
	libxcb-shape.so.0 => /usr/lib/libxcb-shape.so.0 (0x00007fd39e440000)
	libxcb-xfixes.so.0 => /usr/lib/libxcb-xfixes.so.0 (0x00007fd39e436000)
	libSDL2-2.0.so.0 => /usr/lib/libSDL2-2.0.so.0 (0x00007fd39e2a1000)
	libv4l2.so.0 => /usr/lib/libv4l2.so.0 (0x00007fd39e291000)
	libglslang.so.11 => /usr/lib/libglslang.so.11 (0x00007fd39e002000)
	libSPIRV.so => /usr/lib/libSPIRV.so (0x00007fd39d1ca000)
	libepoxy.so.0 => /usr/lib/libepoxy.so.0 (0x00007fd39d098000)
	libpulsecommon-15.0.so => /usr/lib/pulseaudio/libpulsecommon-15.0.so (0x00007fd39d00f000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007fd39cfba000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007fd39cfb1000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007fd39cfa2000)
	libcairo-gobject.so.2 => /usr/lib/libcairo-gobject.so.2 (0x00007fd39cf96000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007fd39cf50000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007fd39cd93000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007fd39cd82000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007fd39cd2e000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fd39ccb7000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fd39cc80000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007fd39cc70000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007fd39cbc8000)
	libogg.so.0 => /usr/lib/libogg.so.0 (0x00007fd39cbbb000)
	libmvec.so.1 => /usr/lib/libmvec.so.1 (0x00007fd39cb8f000)
	libicuuc.so.69 => /usr/lib/libicuuc.so.69 (0x00007fd39c99c000)
	libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x00007fd39c867000)
	libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007fd39c845000)
	libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007fd39c6c1000)
	libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007fd39c6ab000)
	libnettle.so.8 => /usr/lib/libnettle.so.8 (0x00007fd39c664000)
	libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x00007fd39c61b000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fd39c5d7000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fd39c5b0000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fd39c5ab000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fd39c5a3000)
	libv4lconvert.so.0 => /usr/lib/libv4lconvert.so.0 (0x00007fd39c528000)
	libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007fd39c4a6000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007fd39c3e0000)
	libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x00007fd39c3d8000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007fd39c3d3000)
	libtiff.so.5 => /usr/lib/libtiff.so.5 (0x00007fd39c33f000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007fd39c2df000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fd39c2c3000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007fd39c2ab000)
	libthai.so.0 => /usr/lib/libthai.so.0 (0x00007fd39c2a0000)
	libicudata.so.69 => /usr/lib/libicudata.so.69 (0x00007fd39a747000)
	libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x00007fd39a708000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fd39a6fb000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007fd39a5be000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007fd39a568000)
	libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007fd39a55e000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007fd39a537000)
```

**Comment by javsanpar** [comment]
Hello!

Let me check if I can reproduce your problem.

**Comment by javsanpar** [comment]
I can not reproduce your problem.

Can you run storytel-tui this way and attach the file stderr.txt? `RUST_BACKTRACE=1 cargo run 2> /tmp/stderr.txt`

**Comment by bijumon** [comment]
sry about the late reply, busy with work

```
   Compiling autocfg v1.0.1
   Compiling libc v0.2.79
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.46
   Compiling log v0.4.11
   Compiling fnv v1.0.7
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.2
   Compiling memchr v2.3.3
   Compiling pkg-config v0.3.19
   Compiling cc v1.0.61
   Compiling bitflags v1.2.1
   Compiling bytes v0.5.6
   Compiling futures-core v0.3.6
   Compiling itoa v0.4.6
   Compiling pin-project-internal v0.4.27
   Compiling pin-project-lite v0.1.11
   Compiling version_check v0.9.2
   Compiling getrandom v0.2.0
   Compiling once_cell v1.4.1
   Compiling openssl v0.10.30
   Compiling serde_derive v1.0.117
   Compiling foreign-types-shared v0.1.1
   Compiling strsim v0.9.3
   Compiling ident_case v1.0.1
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.6
   Compiling serde v1.0.117
   Compiling futures-sink v0.3.6
   Compiling rustc-serialize v0.3.24
   Compiling tinyvec v0.3.4
   Compiling native-tls v0.2.4
   Compiling httparse v1.3.4
   Compiling hashbrown v0.9.1
   Compiling matches v0.1.8
   Compiling arc-swap v0.4.7
   Compiling ryu v1.0.5
   Compiling try-lock v0.2.3
   Compiling maybe-uninit v2.0.0
   Compiling proc-macro-hack v0.5.18
   Compiling scopeguard v1.1.0
   Compiling openssl-probe v0.1.2
   Compiling smallvec v1.4.2
   Compiling httpdate v0.3.2
   Compiling tower-service v0.3.0
   Compiling encoding_rs v0.8.24
   Compiling serde_json v1.0.59
   Compiling percent-encoding v2.1.0
   Compiling dtoa v0.4.6
   Compiling mime v0.3.16
   Compiling stable_deref_trait v1.2.0
   Compiling array-macro v1.0.5
   Compiling ipnet v2.3.0
   Compiling xi-unicode v0.2.1
   Compiling unicode-width v0.1.8
   Compiling base64 v0.12.3
   Compiling unicode-segmentation v1.6.0
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling num-iter v0.1.41
   Compiling indexmap v1.6.0
   Compiling crossbeam-utils v0.7.2
   Compiling num-complex v0.2.4
   Compiling num-rational v0.2.4
   Compiling tracing-core v0.1.17
   Compiling futures-channel v0.3.6
   Compiling http v0.2.1
   Compiling futures-task v0.3.6
   Compiling unicase v2.6.0
   Compiling foreign-types v0.3.2
   Compiling openssl-sys v0.9.58
   Compiling unicode-normalization v0.1.13
   Compiling unicode-bidi v0.3.4
   Compiling lock_api v0.3.4
   Compiling owning_ref v0.4.1
   Compiling idna v0.2.0
   Compiling tracing v0.1.21
   Compiling want v0.3.0
   Compiling log v0.3.9
   Compiling http-body v0.3.1
   Compiling quote v1.0.7
   Compiling net2 v0.2.35
   Compiling iovec v0.1.4
   Compiling num_cpus v1.13.0
   Compiling rand v0.4.6
   Compiling socket2 v0.3.15
   Compiling parking_lot_core v0.7.2
   Compiling signal-hook-registry v1.2.1
   Compiling time v0.1.44
   Compiling url v2.1.1
   Compiling num-complex v0.1.43
   Compiling num-traits v0.1.43
   Compiling crossbeam-channel v0.4.4
   Compiling mio v0.6.22
   Compiling const-random-macro v0.1.11
   Compiling parking_lot v0.10.2
   Compiling mime_guess v2.0.3
   Compiling num-bigint v0.1.44
   Compiling chrono v0.4.19
   Compiling enum_primitive v0.1.1
   Compiling tokio v0.2.22
   Compiling signal-hook v0.1.16
   Compiling const-random v0.1.11
   Compiling num v0.2.1
   Compiling num-rational v0.1.42
   Compiling crossterm v0.14.2
   Compiling darling_core v0.10.2
   Compiling ahash v0.2.19
   Compiling num v0.1.42
   Compiling tokio-util v0.3.1
   Compiling tokio-tls v0.3.1
   Compiling mpv v0.2.3
   Compiling darling_macro v0.10.2
   Compiling enum-map-derive v0.4.5
   Compiling enum-map v0.6.3
   Compiling darling v0.10.2
   Compiling enumset_derive v0.4.4
   Compiling enumset v0.4.5
   Compiling pin-project v0.4.27
   Compiling futures-util v0.3.6
   Compiling cursive v0.14.1
   Compiling h2 v0.2.6
   Compiling serde_urlencoded v0.6.1
   Compiling hyper v0.13.8
   Compiling hyper-tls v0.4.3
   Compiling reqwest v0.10.8
   Compiling storytel-tui v0.1.0 (/home/user0/storytel-tui)
    Finished dev [unoptimized + debuginfo] target(s) in 54.33s
     Running `target/debug/storytel-tui`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 383) }', src/client_storytel_api.rs:68:66
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.54.0-src/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.54.0-src/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /build/rust/src/rustc-1.54.0-src/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /build/rust/src/rustc-1.54.0-src/library/core/src/result.rs:1037:23
   4: storytel_tui::client_storytel_api::login
             at ./src/client_storytel_api.rs:68:30
   5: storytel_tui::tui::show_check_login
             at ./src/tui.rs:72:9
   6: storytel_tui::tui::show_login::{{closure}}
             at ./src/tui.rs:105:13
   7: cursive::event::Callback::from_fn::{{closure}}
             at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/event.rs:129:13
   8: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /build/rust/src/rustc-1.54.0-src/library/alloc/src/boxed.rs:1589:9
   9: cursive::cursive::Cursive::on_event
             at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:807:52
  10: cursive::cursive::Cursive::process_events
             at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:924:13
  11: cursive::cursive::Cursive::step
             at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:897:34
  12: cursive::cursive::Cursive::run
             at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:883:13
  13: storytel_tui::main
             at ./src/main.rs:32:5
  14: core::ops::function::FnOnce::call_once
             at /build/rust/src/rustc-1.54.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

ps: i wondered if it could be due to a custom bash config !? so I tried the command under pdksh, same result.

**Comment by bijumon** [comment]
> > sry about the late reply, busy with work
> 
> No problem!
> 
> I get the same backtrace if I write my email or password wrong on purpose. If we suppose that you write your email and password correctly, then the bug could be storytel-tui not handling correctly some special characters.

I changed my password to be only characters. no luck

> I am going to change my password to add more special characters and see if I can reproduce your problem.

**Comment by javsanpar** [comment]
Thank you for trying it. I also failed to reproduce the problem using more complex passwords.

What Storytel plan are you using? An unlimited plan or a plan with some kind limitation?

From which country are you trying to use it? If you don't mind to say it.

**Comment by bijumon** [comment]
> Thank you for trying it. I also failed to reproduce the problem using more complex passwords.
> 
> What Storytel plan are you using? An unlimited plan or a plan with some kind limitation?
> 
unlimited with 3 months sub, i dont think there is a limitation 

> From which country are you trying to use it? If you don't mind to say it.
India

ty for the followup

**Comment by javsanpar** [comment]
Hi!

I have been thinking about your problem, and I suspect that Storytel India uses a different API than Storytel Spain.

I don't have an account with a contracted plan with Storytel India with which to study the API. Do you think you could make a capture with mitmproxy of the traffic generated by the Storytel application you have installed on your phone?

**Comment by bijumon** [comment]
yeah! how do I?

**Comment by javsanpar** [comment]
I applied a patch to the project and I think it should fix the problem you had. If you want you can try it again!

**Comment by bijumon** [comment]
> I applied a patch to the project and I think it should fix the problem you had. If you want you can try it again!

works, thank you.

ps: never did get get around to learning mitmproxy, sry :( life after pandemic happened
