### ISSUE TITLE
The TUI closes after entering credentials

### ISSUE THREAD

**Issue by MauritsWilke** [javsanpar/storytel-tui#6]
Hi! After running and entering my credentials, the TUI just closes without any errors.

Is there a way I can fix this or attach a debug log?

**Comment by javsanpar** [comment]
Hi!

Can you apply the attached patch? With this patch, storytel-tui prints the response of Storytel's servers to the stderr. This way, we can see the HTTP response code. Be careful, the response also includes your password hash.

I can help you to apply the patch and read the stderr if you need.

:arrow_down:  [diff.txt](https://github.com/javsanpar/storytel-tui/files/9035108/diff.txt)

**Comment by MauritsWilke** [comment]
how do I apply that? Just copy paste it in the terminal?

**Comment by MauritsWilke** [comment]
Nevermind I think I edited it correctly, logging in however doesn't output anything. How do I read the stderr?

**Comment by javsanpar** [comment]
You can read the stderr redirecting it to a file. For example: run `cargo run 2> /tmp/stderr.txt` or `./storytel-tui 2> /tmp/stderr.txt` and later `cat /tmp/stderr.txt`

**Comment by MauritsWilke** [comment]
Alright, sorry i'm not really experienced with rust. Here is the output:

```
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/storytel-tui`
Ok(
    Response {
        url: "https://www.storytel.com/api/login.action?m=1&uid=<EMAIL>&pwd=<PW>,
        status: 401,
        headers: {
            "date": "Sun, 03 Jul 2022 20:39:43 GMT",
            "content-type": "application/json;charset=UTF-8",
            "content-length": "594",
            "connection": "keep-alive",
            "vary": "CF-Visitor",
            "x-storytel-state": "false",
            "strict-transport-security": "max-age=31536000;includeSubDomains",
            "x-frame-options": "SAMEORIGIN",
            "x-xss-protection": "1;mode=block",
            "x-content-type-options": "nosniff",
            "referrer-policy": "no-referrer-when-downgrade",
            "cache-control": "no-store, max-age=0",
            "via": "1.1 google",
            "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
            "cf-cache-status": "DYNAMIC",
            "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
            "set-cookie": "__cf_bm=H56xNwUox9Lnf.JXyGwEvzV2nxZg3R.o9r8_ZRwPDOA-1656880783-0-AXFzIkASO6DNEn2Jt+O9oPCHICtVOhPuUmtM+M6kfUU1kTmEESn5ElG2dV0bd+GnzgKui2KcyfDNUjcv5UZcDlQ=; path=/; expires=Sun, 03-Jul-22 21:09:43 GMT; domain=.storytel.com; HttpOnly; Secure; SameSite=None",
            "server": "cloudflare",
            "cf-ray": "72526ea26ed70b3f-AMS",
        },
    },
)thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 416) }', src/client_storytel_api.rs:70:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MauritsWilke** [comment]
So I followed the link and:
![image](https://user-images.githubusercontent.com/34707512/177056884-6418e821-f121-4ffb-af0a-16ad862ab581.png)
Seems to be incorrect password but I triple checked (even disabled the `.secret()`) and the login information is correct.

**Comment by javsanpar** [comment]
Could you temporarily change your password to the most simple password possible and try again? To see if storytel-tui is not handling correctly some character.

**Comment by MauritsWilke** [comment]
I just tried with a 10 letter password, no special characters or capitalization. The error message stays the same

**Comment by MauritsWilke** [comment]
![image](https://user-images.githubusercontent.com/34707512/177144450-93f3a1d7-ac75-47a1-a5ab-94caa5819dd3.png)
The URL seems to be the same but instead of URL parameters it uses headers?

**Comment by MauritsWilke** [comment]
Yep

**Comment by javsanpar** [comment]
I have been able to reproduce the bug! It seems that is related to the password length. When I set a pass of 10 char length it fails, but it works with 16 char length.

Now that I can reproduce the bug, I should be able to fix it. It is probably in password_crypt.rs.

In the meanwhile, you can try to set a 16 length pass.

**Comment by MauritsWilke** [comment]
Okay will do! The password I used before trying one of length 10 was 13 characters long.

**Comment by javsanpar** [comment]
Thank you for all your help! :heart:

**Comment by MauritsWilke** [comment]
Thank you for responding to the issue and helping! Also even with a password of length 17 (using a capital letter and a special character) the bug seems to occur. I am fine with sharing some of the passwords I have tried seeing how they are not my real password if you need those for testing!

**Comment by MauritsWilke** [comment]
Oh btw, how did you reverse engineer their password hash?

**Comment by javsanpar** [comment]
Decompiling Storytel android app with jadx and with the help of a friend :smile:

**Comment by MauritsWilke** [comment]
Oh wow thats a lot of effort!

**Comment by javsanpar** [comment]
I uploaded the fix to the repo Now it should work with any password length. Let me know if it works for you.

**Comment by MauritsWilke** [comment]
The login is all working! I can reach my bookshelf and see my books. However, when trying to play a book nothing happens and when I try to pause it afterwards it errors (forwards, backwards and exit all "work" without crashing).

This is the error I get when clicking pause, no error is given when pressing play
```
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/storytel-tui`
thread '<unnamed>' panicked at 'Error setting MPV property: MPV_ERROR_COMMAND', src/mpv.rs:99:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/mpv.rs:20:66
```

**Comment by MauritsWilke** [comment]
I am using Manjaro with Plasma as DE

**Comment by javsanpar** [comment]
Do you have installed mpv?

You can also try storytel-tui aur package: https://aur.archlinux.org/packages/storytel-tui-git.

**Comment by MauritsWilke** [comment]
Yea i have MPV installed, ill try the package!

**Comment by MauritsWilke** [comment]
The package has the same issue sadly. I have MPV installed fairly certain because I can start the app, but do I maybe need some other version?

**Comment by javsanpar** [comment]
Can you run `RUST_BACKTRACE=full storytel-tui 2> /tmp/stderr.txt` and paste here the result?

**Comment by MauritsWilke** [comment]
Oh yea here you go:
```
   Compiling storytel-tui v0.1.0 (/home/maurits/storytel-tui)
    Finished dev [unoptimized + debuginfo] target(s) in 5.00s
     Running `target/debug/storytel-tui`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MPV_ERROR_PROPERTY_UNAVAILABLE', src/mpv.rs:94:74
stack backtrace:
   0:     0x5567ae23677d - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5567ae23677d - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5567ae23677d - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5567ae23677d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5567ae25a24c - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x5567ae230bb1 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x5567ae237f75 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5567ae237f75 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5567ae237f75 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x5567ae237be9 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x5567ae238548 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x5567ae2383f7 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x5567ae236c34 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5567ae238129 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x5567adc30043 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x5567adc30133 - core::result::unwrap_failed::h995262f85f9c4e2c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
  16:     0x5567adc5cbd0 - core::result::Result<T,E>::unwrap::h0ce41ee91a7c317c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
  17:     0x5567adc75221 - storytel_tui::mpv::simple_example::{{closure}}::h6a83c50238e85a7e
                               at /home/maurits/storytel-tui/src/mpv.rs:94:45
  18:     0x5567adc6e98c - std::sys_common::backtrace::__rust_begin_short_backtrace::hcb8933036bea7ed7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:122:18
  19:     0x5567adc44cd0 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h4f4712f1f687a7b8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:501:17
  20:     0x5567adc7f470 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf6189a6e4b285477
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panic/unwind_safe.rs:271:9
  21:     0x5567adc6485a - std::panicking::try::do_call::h796dc973996b0085
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  22:     0x5567adc6492b - __rust_try
  23:     0x5567adc64791 - std::panicking::try::hafc6266c17b7ac78
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  24:     0x5567adc56160 - std::panic::catch_unwind::h57c0dd795c121c2c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  25:     0x5567adc44ad3 - std::thread::Builder::spawn_unchecked_::{{closure}}::h73324a3842b38d2d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:500:30
  26:     0x5567adc5061e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e52f740e7c65b21
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  27:     0x5567ae23cf13 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcbca3baf872b7fe4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  28:     0x5567ae23cf13 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h18790338ce1743e2
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  29:     0x5567ae23cf13 - std::sys::unix::thread::Thread::new::thread_start::hb1067183bad48893
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys/unix/thread.rs:108:17
  30:     0x7fdb8114e54d - <unknown>
  31:     0x7fdb811d3874 - clone
  32:                0x0 - <unknown>
[mp3 @ 0x7fdb1c005680] Failed to read frame size: Could not seek to 1026.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/mpv.rs:20:66
stack backtrace:
   0:     0x5567ae23677d - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5567ae23677d - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5567ae23677d - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5567ae23677d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5567ae25a24c - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x5567ae230bb1 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x5567ae237f75 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5567ae237f75 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5567ae237f75 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x5567ae237be9 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x5567ae238548 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x5567ae2383f7 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x5567ae236c34 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5567ae238129 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x5567adc30043 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x5567adc30133 - core::result::unwrap_failed::h995262f85f9c4e2c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
  16:     0x5567adc5cdb6 - core::result::Result<T,E>::unwrap::h418395f18af610e2
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
  17:     0x5567adc738da - storytel_tui::mpv::pause::h299b46375c56aea0
                               at /home/maurits/storytel-tui/src/mpv.rs:20:20
  18:     0x5567adc50328 - core::ops::function::Fn::call::h7348b961d0549534
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:77:5
  19:     0x5567adc4bd9b - cursive::event::Callback::from_fn::{{closure}}::hf7a5d58adcbba996
                               at /home/maurits/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/event.rs:129:13
  20:     0x5567ae119313 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h39f95ce70f5eefbd
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1886:9
  21:     0x5567ae12cf78 - cursive::cursive::Cursive::on_event::h0a4784f9cd883db4
                               at /home/maurits/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:807:52
  22:     0x5567ae12d60c - cursive::cursive::Cursive::process_events::h7019369343f60093
                               at /home/maurits/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:924:13
  23:     0x5567ae12d544 - cursive::cursive::Cursive::step::h2199708d51d8c7a8
                               at /home/maurits/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:897:34
  24:     0x5567ae12d529 - cursive::cursive::Cursive::run::hf4833ae61e66bebf
                               at /home/maurits/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive-0.14.1/src/cursive.rs:883:13
  25:     0x5567adc5655d - storytel_tui::main::hce33a62dcb622847
                               at /home/maurits/storytel-tui/src/main.rs:32:5
  26:     0x5567adc50e4b - core::ops::function::FnOnce::call_once::hc75fcadaf0bf4856
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  27:     0x5567adc6e93e - std::sys_common::backtrace::__rust_begin_short_backtrace::h7e2a45eea97d5485
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:122:18
  28:     0x5567adc4c421 - std::rt::lang_start::{{closure}}::h3e97909a50702639
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:145:18
  29:     0x5567ae22c80e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf833e7144973d4be
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
  30:     0x5567ae22c80e - std::panicking::try::do_call::h79761d203bfb6b46
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  31:     0x5567ae22c80e - std::panicking::try::h0561cbbe1722251d
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  32:     0x5567ae22c80e - std::panic::catch_unwind::hbca347ddd031b141
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  33:     0x5567ae22c80e - std::rt::lang_start_internal::{{closure}}::h0492050ad281ec32
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
  34:     0x5567ae22c80e - std::panicking::try::do_call::h3ebce69871996bb3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  35:     0x5567ae22c80e - std::panicking::try::hbed537d20e728475
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  36:     0x5567ae22c80e - std::panic::catch_unwind::h4185e2024c6a5d05
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  37:     0x5567ae22c80e - std::rt::lang_start_internal::h1899cfd715ca6829
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
  38:     0x5567adc4c3f0 - std::rt::lang_start::h6b879bb2dbac5a14
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:144:17
  39:     0x5567adc565cc - main
  40:     0x7fdb810eb290 - <unknown>
  41:     0x7fdb810eb34a - __libc_start_main
  42:     0x5567adc30335 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  43:                0x0 - <unknown>
```

**Comment by javsanpar** [comment]
I am going to move this bug to a new issue.
