### ISSUE TITLE
Crash when pausing an audiobook 

### ISSUE THREAD

**Issue by javsanpar** [javsanpar/storytel-tui#7]
The login is all working! I can reach my bookshelf and see my books. However, when trying to play a book nothing happens and when I try to pause it afterwards it errors (forwards, backwards and exit all "work" without crashing).

This is the error I get when clicking pause, no error is given when pressing play
```
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/storytel-tui`
thread '<unnamed>' panicked at 'Error setting MPV property: MPV_ERROR_COMMAND', src/mpv.rs:99:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', src/mpv.rs:20:66
```

_Originally posted by @MauritsWilke in https://github.com/javsanpar/storytel-tui/issues/6#issuecomment-1174858557_

**Comment by javsanpar** [comment]
I have managed to reproduce the problem!

storytel-tui crash if the user press <Pause> button before the audiobook starts playing.

@MauritsWilke, can you try to reproduce an audiobook and wait a reasonable time :smile: for it to start? If the audiobook is short, it should take less to load.

**Comment by MauritsWilke** [comment]
Yep it was just me being impatient! It's all working now, thanks a lot!

**Comment by javsanpar** [comment]
Perfect! Anyway, my intention is to fix this bug.
